from . import pharmacy_common
from . import pharmacy_branch
from . import pharmacy_product
from . import pharmacy_batch
from . import pharmacy_inventory
from . import pharmacy_purchase
from . import pharmacy_pos
from . import pharmacy_prescription
from . import pharmacy_customer
from . import pharmacy_accounting
from . import pharmacy_dashboard
